8Ô∏è‚É£ Performance Optimization
üìå Handling large datasets efficiently

In [1]:
import pandas as pd
df=pd.read_csv('weather.csv')

In [ ]:
df.memory_usage(deep=True)
#This is used to know the memory usage off the data frame

Index                 132
Date                 1180
Time                 1080
City                 1140
Temperature_C         160
Humidity_%            160
Wind_Speed_kmph       160
Weather_Condition    1084
Precipitation_mm      160
Air_Quality_Index     160
UV_Index              160
Is_Weekend             20
Remarks              1072
dtype: int64

In [11]:
df.head()

,Date,Time,City,Temperature_C,Humidity_%,Wind_Speed_kmph,Weather_Condition,Precipitation_mm,Air_Quality_Index,UV_Index,Is_Weekend,Remarks
0,2024-01-01,08:00,New York,5.0,80,10,Cloudy,2.5,45,2,False,Cold
1,2024-01-02,12:00,Los Angeles,12.0,65,15,Sunny,0.0,30,5,False,Warm
2,2024-01-03,16:00,Chicago,8.0,70,20,Rainy,10.0,60,3,False,Wet
3,2024-01-04,20:00,Houston,NaN,55,5,Clear,0.0,25,7,True,Clear Night
4,2024-01-05,23:00,Phoenix,20.0,40,12,Sunny,0.5,70,6,True,Hot

In [ ]:
df=df.astype({'City':'category'})
print(df.dtypes)
#Converts columns to category to save memory

Date                   object
Time                   object
City                 category
Temperature_C         float64
Humidity_%              int64
Wind_Speed_kmph         int64
Weather_Condition      object
Precipitation_mm      float64
Air_Quality_Index       int64
UV_Index                int64
Is_Weekend               bool
Remarks                object
dtype: object

In [ ]:
for index, row in df.iterrows():
    print(f"Row {index}: {row['City']} has temperature {row['Temperature_C']}¬∞C with {row['Weather_Condition']}.")

# allow you to iterate over rows in a Pandas DataFrame but is slower and more felxible

Row 0: New York has temperature 5.0¬∞C with Cloudy.
Row 1: Los Angeles has temperature 12.0¬∞C with Sunny.
Row 2: Chicago has temperature 8.0¬∞C with Rainy.
Row 3: Houston has temperature nan¬∞C with Clear.
Row 4: Phoenix has temperature 20.0¬∞C with Sunny.
Row 5: New York has temperature 15.0¬∞C with Cloudy.
Row 6: Los Angeles has temperature 18.0¬∞C with Sunny.
Row 7: Chicago has temperature 22.0¬∞C with Rainy.
Row 8: Houston has temperature nan¬∞C with Clear.
Row 9: Phoenix has temperature 30.0¬∞C with Sunny.
Row 10: New York has temperature 5.0¬∞C with Cloudy.
Row 11: Los Angeles has temperature 12.0¬∞C with Sunny.
Row 12: Chicago has temperature 8.0¬∞C with Rainy.
Row 13: Houston has temperature nan¬∞C with Clear.
Row 14: Phoenix has temperature 20.0¬∞C with Sunny.
Row 15: New York has temperature 15.0¬∞C with Cloudy.
Row 16: Los Angeles has temperature 18.0¬∞C with Sunny.
Row 17: Chicago has temperature 22.0¬∞C with Rainy.
Row 18: Chicago has temperature 8.0¬∞C with Rainy.
Row 19: Chicago has temperature 22.0¬∞C with Rainy.

In [ ]:
for row in df.itertuples(index=False):
    print(f"{row.City} -{row.Temperature_C}¬∞C -{row.Weather_Condition}")
    
#allow you to iterate over rows in a Pandas DataFrame , is faster and more efficient

New York -5.0¬∞C -Cloudy
Los Angeles -12.0¬∞C -Sunny
Chicago -8.0¬∞C -Rainy
Houston -nan¬∞C -Clear
Phoenix -20.0¬∞C -Sunny
New York -15.0¬∞C -Cloudy
Los Angeles -18.0¬∞C -Sunny
Chicago -22.0¬∞C -Rainy
Houston -nan¬∞C -Clear
Phoenix -30.0¬∞C -Sunny
New York -5.0¬∞C -Cloudy
Los Angeles -12.0¬∞C -Sunny
Chicago -8.0¬∞C -Rainy
Houston -nan¬∞C -Clear
Phoenix -20.0¬∞C -Sunny
New York -15.0¬∞C -Cloudy
Los Angeles -18.0¬∞C -Sunny
Chicago -22.0¬∞C -Rainy
Chicago -8.0¬∞C -Rainy
Chicago -22.0¬∞C -Rainy

In [ ]:
df.query('Temperature_C > 20')
#The .query() method in pandas allows filtering DataFrame rows based on a condition using a string expression.

,Date,Time,City,Temperature_C,Humidity_%,Wind_Speed_kmph,Weather_Condition,Precipitation_mm,Air_Quality_Index,UV_Index,Is_Weekend,Remarks
7,2024-01-08,16:00,Chicago,22.0,50,9,Rainy,5.0,65,5,False,Wet
9,2024-01-10,23:00,Phoenix,30.0,35,7,Sunny,3.0,20,6,True,Hot
17,2024-01-08,16:00,Chicago,22.0,50,9,Rainy,5.0,65,5,False,Wet
19,2024-01-08,16:00,Chicago,22.0,50,9,Rainy,5.0,65,5,False,Wet