2Ô∏è‚É£ Data Cleaning & Preprocessing
üìå Handling missing, duplicate, and incorrect values

In [2]:
import pandas as pd

df=pd.read_csv('weather.csv')
df

,Date,Time,City,Temperature_C,Humidity_%,Wind_Speed_kmph,Weather_Condition,Precipitation_mm,Air_Quality_Index,UV_Index,Is_Weekend,Remarks
0,2024-01-01,08:00,New York,5.0,80,10,Cloudy,2.5,45,2,False,Cold
1,2024-01-02,12:00,Los Angeles,12.0,65,15,Sunny,0.0,30,5,False,Warm
2,2024-01-03,16:00,Chicago,8.0,70,20,Rainy,10.0,60,3,False,Wet
3,2024-01-04,20:00,Houston,NaN,55,5,Clear,0.0,25,7,True,Clear Night
4,2024-01-05,23:00,Phoenix,20.0,40,12,Sunny,0.5,70,6,True,Hot
5,2024-01-06,08:00,New York,15.0,60,14,Cloudy,1.2,50,4,False,Cold
6,2024-01-07,12:00,Los Angeles,18.0,75,11,Sunny,0.0,40,3,False,Warm
7,2024-01-08,16:00,Chicago,22.0,50,9,Rainy,5.0,65,5,False,Wet
8,2024-01-09,20:00,Houston,NaN,45,8,Clear,0.0,55,2,True,Clear Night
9,2024-01-10,23:00,Phoenix,30.0,35,7,Sunny,3.0,20,6,True,Hot
10,2024-01-01,08:00,New York,5.0,80,10,Cloudy,2.5,45,2,False,Cold
11,2024-01-02,12:00,Los Angeles,12.0,65,15,Sunny,0.0,30,5,False,Warm
12,2024-01-03,16:00,Chicago,8.0,70,20,Rainy,10.0,60,3,False,Wet
13,2024-01-04,20:00,Houston,NaN,55,5,Clear,0.0,25,7,True,Clear Night
14,2024-01-05,23:00,Phoenix,20.0,40,12,Sunny,0.5,70,6,True,Hot
15,2024-01-06,08:00,New York,15.0,60,14,Cloudy,1.2,50,4,False,Cold
16,2024-01-07,12:00,Los Angeles,18.0,75,11,Sunny,0.0,40,3,False,Warm
17,2024-01-08,16:00,Chicago,22.0,50,9,Rainy,5.0,65,5,False,Wet
18,2024-01-03,16:00,Chicago,8.0,70,20,Rainy,10.0,60,3,False,Wet
19,2024-01-08,16:00,Chicago,22.0,50,9,Rainy,5.0,65,5,False,Wet

In [2]:
df.isnull().sum()
#provide us with the count of null values in the dataset for all the columns

Date                 0
Time                 0
City                 0
Temperature_C        3
Humidity_%           0
Wind_Speed_kmph      0
Weather_Condition    0
Precipitation_mm     0
Air_Quality_Index    0
UV_Index             0
Is_Weekend           0
Remarks              0
dtype: int64

In [3]:
df['Temperature_C']=df['Temperature_C'].fillna(df['Temperature_C'].mean())
#Here we had null values in the "Temperature_C" column so we filled the missing vlaues with the mean,
#you can also fill it with other methods like forward fill (ffill) and backward fill(bfill)
#to know about them more visit the pandas fillna documentation

In [ ]:
df.dropna()
#Thsi will drop or remove all the rows/columns with missing values

,Date,Time,City,Temperature_C,Humidity_%,Wind_Speed_kmph,Weather_Condition,Precipitation_mm,Air_Quality_Index,UV_Index,Is_Weekend,Remarks
0,2024-01-01,08:00,New York,5.000000,80,10,Cloudy,2.5,45,2,False,Cold
1,2024-01-02,12:00,Los Angeles,12.000000,65,15,Sunny,0.0,30,5,False,Warm
2,2024-01-03,16:00,Chicago,8.000000,70,20,Rainy,10.0,60,3,False,Wet
3,2024-01-04,20:00,Houston,15.294118,55,5,Clear,0.0,25,7,True,Clear Night
4,2024-01-05,23:00,Phoenix,20.000000,40,12,Sunny,0.5,70,6,True,Hot
5,2024-01-06,08:00,New York,15.000000,60,14,Cloudy,1.2,50,4,False,Cold
6,2024-01-07,12:00,Los Angeles,18.000000,75,11,Sunny,0.0,40,3,False,Warm
7,2024-01-08,16:00,Chicago,22.000000,50,9,Rainy,5.0,65,5,False,Wet
8,2024-01-09,20:00,Houston,15.294118,45,8,Clear,0.0,55,2,True,Clear Night
9,2024-01-10,23:00,Phoenix,30.000000,35,7,Sunny,3.0,20,6,True,Hot
10,2024-01-01,08:00,New York,5.000000,80,10,Cloudy,2.5,45,2,False,Cold
11,2024-01-02,12:00,Los Angeles,12.000000,65,15,Sunny,0.0,30,5,False,Warm
12,2024-01-03,16:00,Chicago,8.000000,70,20,Rainy,10.0,60,3,False,Wet
13,2024-01-04,20:00,Houston,15.294118,55,5,Clear,0.0,25,7,True,Clear Night
14,2024-01-05,23:00,Phoenix,20.000000,40,12,Sunny,0.5,70,6,True,Hot
15,2024-01-06,08:00,New York,15.000000,60,14,Cloudy,1.2,50,4,False,Cold
16,2024-01-07,12:00,Los Angeles,18.000000,75,11,Sunny,0.0,40,3,False,Warm
17,2024-01-08,16:00,Chicago,22.000000,50,9,Rainy,5.0,65,5,False,Wet
18,2024-01-03,16:00,Chicago,8.000000,70,20,Rainy,10.0,60,3,False,Wet
19,2024-01-08,16:00,Chicago,22.000000,50,9,Rainy,5.0,65,5,False,Wet

In [ ]:
df.duplicated()
#This will identify the duplicates in the dataset

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19     True
dtype: bool

In [7]:
df.drop_duplicates()
#This removes all the rows with the duplicate values

,Date,Time,City,Temperature_C,Humidity_%,Wind_Speed_kmph,Weather_Condition,Precipitation_mm,Air_Quality_Index,UV_Index,Is_Weekend,Remarks
0,2024-01-01,08:00,New York,5.000000,80,10,Cloudy,2.5,45,2,False,Cold
1,2024-01-02,12:00,Los Angeles,12.000000,65,15,Sunny,0.0,30,5,False,Warm
2,2024-01-03,16:00,Chicago,8.000000,70,20,Rainy,10.0,60,3,False,Wet
3,2024-01-04,20:00,Houston,15.294118,55,5,Clear,0.0,25,7,True,Clear Night
4,2024-01-05,23:00,Phoenix,20.000000,40,12,Sunny,0.5,70,6,True,Hot
5,2024-01-06,08:00,New York,15.000000,60,14,Cloudy,1.2,50,4,False,Cold
6,2024-01-07,12:00,Los Angeles,18.000000,75,11,Sunny,0.0,40,3,False,Warm
7,2024-01-08,16:00,Chicago,22.000000,50,9,Rainy,5.0,65,5,False,Wet
8,2024-01-09,20:00,Houston,15.294118,45,8,Clear,0.0,55,2,True,Clear Night
9,2024-01-10,23:00,Phoenix,30.000000,35,7,Sunny,3.0,20,6,True,Hot

In [17]:
df.drop_duplicates()
#This removes all the rows with the duplicate values

,Date,Time,City,Temperature_C,Humidity_%,Wind_Speed_kmph,Weather_Condition,Precipitation_mm,Air_Quality_Index,UV_Index,Is_Weekend,Remarks
0,2024-01-01,08:00,New York,5,80,10,Cloudy,2.5,45,2,False,Cold
1,2024-01-02,12:00,Los Angeles,12,65,15,Sunny,0.0,30,5,False,Warm
2,2024-01-03,16:00,Chicago,8,70,20,Rainy,10.0,60,3,False,Wet
3,2024-01-04,20:00,Houston,15,55,5,Clear,0.0,25,7,True,Clear Night
4,2024-01-05,23:00,Phoenix,20,40,12,Sunny,0.5,70,6,True,Hot
5,2024-01-06,08:00,New York,15,60,14,Cloudy,1.2,50,4,False,Cold
6,2024-01-07,12:00,Los Angeles,18,75,11,Sunny,0.0,40,3,False,Warm
7,2024-01-08,16:00,Chicago,22,50,9,Rainy,5.0,65,5,False,Wet
8,2024-01-09,20:00,Houston,15,45,8,Clear,0.0,55,2,True,Clear Night
9,2024-01-10,23:00,Phoenix,30,35,7,Sunny,3.0,20,6,True,Hot

In [20]:
df['Temperature_C'].dtype

dtype('float64')

In [ ]:
df['Temperature_C']=df['Temperature_C'].astype(dtype=int)
df['Temperature_C'].dtype
#This astype() function changes the data type of a column, as you can see above the data type of 
# column temperature was float but after performing this the data type of column temperature became int

dtype('int32')

In [ ]:
pd.to_datetime(df['Date'])
#This changes the column to datetime format

0    2024-01-01
1    2024-01-02
2    2024-01-03
3    2024-01-04
4    2024-01-05
5    2024-01-06
6    2024-01-07
7    2024-01-08
8    2024-01-09
9    2024-01-10
10   2024-01-01
11   2024-01-02
12   2024-01-03
13   2024-01-04
14   2024-01-05
15   2024-01-06
16   2024-01-07
17   2024-01-08
18   2024-01-03
19   2024-01-08
Name: Date, dtype: datetime64[ns]

In [ ]:
df.replace('New York','N.Y')
#This function replaces the values in the columns as here i replaced New York with N.Y

,Date,Time,City,Temperature_C,Humidity_%,Wind_Speed_kmph,Weather_Condition,Precipitation_mm,Air_Quality_Index,UV_Index,Is_Weekend,Remarks
0,2024-01-01,08:00,N.Y,5.0,80,10,Cloudy,2.5,45,2,False,Cold
1,2024-01-02,12:00,Los Angeles,12.0,65,15,Sunny,0.0,30,5,False,Warm
2,2024-01-03,16:00,Chicago,8.0,70,20,Rainy,10.0,60,3,False,Wet
3,2024-01-04,20:00,Houston,NaN,55,5,Clear,0.0,25,7,True,Clear Night
4,2024-01-05,23:00,Phoenix,20.0,40,12,Sunny,0.5,70,6,True,Hot
5,2024-01-06,08:00,N.Y,15.0,60,14,Cloudy,1.2,50,4,False,Cold
6,2024-01-07,12:00,Los Angeles,18.0,75,11,Sunny,0.0,40,3,False,Warm
7,2024-01-08,16:00,Chicago,22.0,50,9,Rainy,5.0,65,5,False,Wet
8,2024-01-09,20:00,Houston,NaN,45,8,Clear,0.0,55,2,True,Clear Night
9,2024-01-10,23:00,Phoenix,30.0,35,7,Sunny,3.0,20,6,True,Hot
10,2024-01-01,08:00,N.Y,5.0,80,10,Cloudy,2.5,45,2,False,Cold
11,2024-01-02,12:00,Los Angeles,12.0,65,15,Sunny,0.0,30,5,False,Warm
12,2024-01-03,16:00,Chicago,8.0,70,20,Rainy,10.0,60,3,False,Wet
13,2024-01-04,20:00,Houston,NaN,55,5,Clear,0.0,25,7,True,Clear Night
14,2024-01-05,23:00,Phoenix,20.0,40,12,Sunny,0.5,70,6,True,Hot
15,2024-01-06,08:00,N.Y,15.0,60,14,Cloudy,1.2,50,4,False,Cold
16,2024-01-07,12:00,Los Angeles,18.0,75,11,Sunny,0.0,40,3,False,Warm
17,2024-01-08,16:00,Chicago,22.0,50,9,Rainy,5.0,65,5,False,Wet
18,2024-01-03,16:00,Chicago,8.0,70,20,Rainy,10.0,60,3,False,Wet
19,2024-01-08,16:00,Chicago,22.0,50,9,Rainy,5.0,65,5,False,Wet

In [ ]:
df.rename(columns={'Temperature_C':'Temp_C'})
#Changes the column name, Temperature_C changed to Temp_C

,Date,Time,City,Temp_C,Humidity_%,Wind_Speed_kmph,Weather_Condition,Precipitation_mm,Air_Quality_Index,UV_Index,Is_Weekend,Remarks
0,2024-01-01,08:00,New York,5.0,80,10,Cloudy,2.5,45,2,False,Cold
1,2024-01-02,12:00,Los Angeles,12.0,65,15,Sunny,0.0,30,5,False,Warm
2,2024-01-03,16:00,Chicago,8.0,70,20,Rainy,10.0,60,3,False,Wet
3,2024-01-04,20:00,Houston,NaN,55,5,Clear,0.0,25,7,True,Clear Night
4,2024-01-05,23:00,Phoenix,20.0,40,12,Sunny,0.5,70,6,True,Hot
5,2024-01-06,08:00,New York,15.0,60,14,Cloudy,1.2,50,4,False,Cold
6,2024-01-07,12:00,Los Angeles,18.0,75,11,Sunny,0.0,40,3,False,Warm
7,2024-01-08,16:00,Chicago,22.0,50,9,Rainy,5.0,65,5,False,Wet
8,2024-01-09,20:00,Houston,NaN,45,8,Clear,0.0,55,2,True,Clear Night
9,2024-01-10,23:00,Phoenix,30.0,35,7,Sunny,3.0,20,6,True,Hot
10,2024-01-01,08:00,New York,5.0,80,10,Cloudy,2.5,45,2,False,Cold
11,2024-01-02,12:00,Los Angeles,12.0,65,15,Sunny,0.0,30,5,False,Warm
12,2024-01-03,16:00,Chicago,8.0,70,20,Rainy,10.0,60,3,False,Wet
13,2024-01-04,20:00,Houston,NaN,55,5,Clear,0.0,25,7,True,Clear Night
14,2024-01-05,23:00,Phoenix,20.0,40,12,Sunny,0.5,70,6,True,Hot
15,2024-01-06,08:00,New York,15.0,60,14,Cloudy,1.2,50,4,False,Cold
16,2024-01-07,12:00,Los Angeles,18.0,75,11,Sunny,0.0,40,3,False,Warm
17,2024-01-08,16:00,Chicago,22.0,50,9,Rainy,5.0,65,5,False,Wet
18,2024-01-03,16:00,Chicago,8.0,70,20,Rainy,10.0,60,3,False,Wet
19,2024-01-08,16:00,Chicago,22.0,50,9,Rainy,5.0,65,5,False,Wet

In [16]:
def mean_wind(x):
    if pd.isna(x):
        return df['Wind_Speed_kmph'].mean()
    else:
        return x
df['Wind_Speed_kmph']=df['Wind_Speed_kmph'].apply(func=mean_wind)
df

# In this the apply() function is used to apply function to a column in the data frame
#here I created a function which will replace all the NaN values with the mean for the wind_speed_kmph column.

,Date,Time,City,Temperature_C,Humidity_%,Wind_Speed_kmph,Weather_Condition,Precipitation_mm,Air_Quality_Index,UV_Index,Is_Weekend,Remarks
0,2024-01-01,08:00,New York,5.0,80,10,Cloudy,2.5,45,2,False,Cold
1,2024-01-02,12:00,Los Angeles,12.0,65,15,Sunny,0.0,30,5,False,Warm
2,2024-01-03,16:00,Chicago,8.0,70,20,Rainy,10.0,60,3,False,Wet
3,2024-01-04,20:00,Houston,NaN,55,5,Clear,0.0,25,7,True,Clear Night
4,2024-01-05,23:00,Phoenix,20.0,40,12,Sunny,0.5,70,6,True,Hot
5,2024-01-06,08:00,New York,15.0,60,14,Cloudy,1.2,50,4,False,Cold
6,2024-01-07,12:00,Los Angeles,18.0,75,11,Sunny,0.0,40,3,False,Warm
7,2024-01-08,16:00,Chicago,22.0,50,9,Rainy,5.0,65,5,False,Wet
8,2024-01-09,20:00,Houston,NaN,45,8,Clear,0.0,55,2,True,Clear Night
9,2024-01-10,23:00,Phoenix,30.0,35,7,Sunny,3.0,20,6,True,Hot
10,2024-01-01,08:00,New York,5.0,80,10,Cloudy,2.5,45,2,False,Cold
11,2024-01-02,12:00,Los Angeles,12.0,65,15,Sunny,0.0,30,5,False,Warm
12,2024-01-03,16:00,Chicago,8.0,70,20,Rainy,10.0,60,3,False,Wet
13,2024-01-04,20:00,Houston,NaN,55,5,Clear,0.0,25,7,True,Clear Night
14,2024-01-05,23:00,Phoenix,20.0,40,12,Sunny,0.5,70,6,True,Hot
15,2024-01-06,08:00,New York,15.0,60,14,Cloudy,1.2,50,4,False,Cold
16,2024-01-07,12:00,Los Angeles,18.0,75,11,Sunny,0.0,40,3,False,Warm
17,2024-01-08,16:00,Chicago,22.0,50,9,Rainy,5.0,65,5,False,Wet
18,2024-01-03,16:00,Chicago,8.0,70,20,Rainy,10.0,60,3,False,Wet
19,2024-01-08,16:00,Chicago,22.0,50,9,Rainy,5.0,65,5,False,Wet