7Ô∏è‚É£ Data Merging 
üìå Combining multiple datasets

In [1]:
import pandas as pd

df= pd.read_csv('weather.csv')

In [2]:
df.head()

,Date,Time,City,Temperature_C,Humidity_%,Wind_Speed_kmph,Weather_Condition,Precipitation_mm,Air_Quality_Index,UV_Index,Is_Weekend,Remarks
0,2024-01-01,08:00,New York,5.0,80,10,Cloudy,2.5,45,2,False,Cold
1,2024-01-02,12:00,Los Angeles,12.0,65,15,Sunny,0.0,30,5,False,Warm
2,2024-01-03,16:00,Chicago,8.0,70,20,Rainy,10.0,60,3,False,Wet
3,2024-01-04,20:00,Houston,NaN,55,5,Clear,0.0,25,7,True,Clear Night
4,2024-01-05,23:00,Phoenix,20.0,40,12,Sunny,0.5,70,6,True,Hot

In [3]:
df1=df[['City','Remarks','Weather_Condition','Date']]

df2=df[['Temperature_C','Humidity_%','Date']]

In [4]:
pd.concat([df1,df2],axis=1)
# Using concat command we can concat 2 df's. Axis is default 0 so if you want like this output then 
# set the axis to 1 otherwise leave it to default

,City,Remarks,Weather_Condition,Date,Temperature_C,Humidity_%,Date
0,New York,Cold,Cloudy,2024-01-01,5.0,80,2024-01-01
1,Los Angeles,Warm,Sunny,2024-01-02,12.0,65,2024-01-02
2,Chicago,Wet,Rainy,2024-01-03,8.0,70,2024-01-03
3,Houston,Clear Night,Clear,2024-01-04,NaN,55,2024-01-04
4,Phoenix,Hot,Sunny,2024-01-05,20.0,40,2024-01-05
5,New York,Cold,Cloudy,2024-01-06,15.0,60,2024-01-06
6,Los Angeles,Warm,Sunny,2024-01-07,18.0,75,2024-01-07
7,Chicago,Wet,Rainy,2024-01-08,22.0,50,2024-01-08
8,Houston,Clear Night,Clear,2024-01-09,NaN,45,2024-01-09
9,Phoenix,Hot,Sunny,2024-01-10,30.0,35,2024-01-10
10,New York,Cold,Cloudy,2024-01-01,5.0,80,2024-01-01
11,Los Angeles,Warm,Sunny,2024-01-02,12.0,65,2024-01-02
12,Chicago,Wet,Rainy,2024-01-03,8.0,70,2024-01-03
13,Houston,Clear Night,Clear,2024-01-04,NaN,55,2024-01-04
14,Phoenix,Hot,Sunny,2024-01-05,20.0,40,2024-01-05
15,New York,Cold,Cloudy,2024-01-06,15.0,60,2024-01-06
16,Los Angeles,Warm,Sunny,2024-01-07,18.0,75,2024-01-07
17,Chicago,Wet,Rainy,2024-01-08,22.0,50,2024-01-08
18,Chicago,Wet,Rainy,2024-01-03,8.0,70,2024-01-03
19,Chicago,Wet,Rainy,2024-01-08,22.0,50,2024-01-08

In [5]:
pd.merge(df1,df2, on='Date',how='inner')
# Merge() function acts as SQL join for data frames , we join the df's on the common key column.

,City,Remarks,Weather_Condition,Date,Temperature_C,Humidity_%
0,New York,Cold,Cloudy,2024-01-01,5.0,80
1,New York,Cold,Cloudy,2024-01-01,5.0,80
2,Los Angeles,Warm,Sunny,2024-01-02,12.0,65
3,Los Angeles,Warm,Sunny,2024-01-02,12.0,65
4,Chicago,Wet,Rainy,2024-01-03,8.0,70
5,Chicago,Wet,Rainy,2024-01-03,8.0,70
6,Chicago,Wet,Rainy,2024-01-03,8.0,70
7,Houston,Clear Night,Clear,2024-01-04,NaN,55
8,Houston,Clear Night,Clear,2024-01-04,NaN,55
9,Phoenix,Hot,Sunny,2024-01-05,20.0,40
10,Phoenix,Hot,Sunny,2024-01-05,20.0,40
11,New York,Cold,Cloudy,2024-01-06,15.0,60
12,New York,Cold,Cloudy,2024-01-06,15.0,60
13,Los Angeles,Warm,Sunny,2024-01-07,18.0,75
14,Los Angeles,Warm,Sunny,2024-01-07,18.0,75
15,Chicago,Wet,Rainy,2024-01-08,22.0,50
16,Chicago,Wet,Rainy,2024-01-08,22.0,50
17,Chicago,Wet,Rainy,2024-01-08,22.0,50
18,Houston,Clear Night,Clear,2024-01-09,NaN,45
19,Phoenix,Hot,Sunny,2024-01-10,30.0,35
20,New York,Cold,Cloudy,2024-01-01,5.0,80
21,New York,Cold,Cloudy,2024-01-01,5.0,80
22,Los Angeles,Warm,Sunny,2024-01-02,12.0,65
23,Los Angeles,Warm,Sunny,2024-01-02,12.0,65
24,Chicago,Wet,Rainy,2024-01-03,8.0,70
25,Chicago,Wet,Rainy,2024-01-03,8.0,70
26,Chicago,Wet,Rainy,2024-01-03,8.0,70
27,Houston,Clear Night,Clear,2024-01-04,NaN,55
28,Houston,Clear Night,Clear,2024-01-04,NaN,55
29,Phoenix,Hot,Sunny,2024-01-05,20.0,40
30,Phoenix,Hot,Sunny,2024-01-05,20.0,40
31,New York,Cold,Cloudy,2024-01-06,15.0,60
32,New York,Cold,Cloudy,2024-01-06,15.0,60
33,Los Angeles,Warm,Sunny,2024-01-07,18.0,75
34,Los Angeles,Warm,Sunny,2024-01-07,18.0,75
35,Chicago,Wet,Rainy,2024-01-08,22.0,50
36,Chicago,Wet,Rainy,2024-01-08,22.0,50
37,Chicago,Wet,Rainy,2024-01-08,22.0,50
38,Chicago,Wet,Rainy,2024-01-03,8.0,70
39,Chicago,Wet,Rainy,2024-01-03,8.0,70
40,Chicago,Wet,Rainy,2024-01-03,8.0,70
41,Chicago,Wet,Rainy,2024-01-08,22.0,50
42,Chicago,Wet,Rainy,2024-01-08,22.0,50
43,Chicago,Wet,Rainy,2024-01-08,22.0,50