3Ô∏è‚É£ Data Selection & Filtering
üìå Extracting relevant data

In [2]:
import pandas as pd

df=pd.read_csv("weather.csv")
df

,Date,Time,City,Temperature_C,Humidity_%,Wind_Speed_kmph,Weather_Condition,Precipitation_mm,Air_Quality_Index,UV_Index,Is_Weekend,Remarks
0,2024-01-01,08:00,New York,5.0,80,10,Cloudy,2.5,45,2,False,Cold
1,2024-01-02,12:00,Los Angeles,12.0,65,15,Sunny,0.0,30,5,False,Warm
2,2024-01-03,16:00,Chicago,8.0,70,20,Rainy,10.0,60,3,False,Wet
3,2024-01-04,20:00,Houston,NaN,55,5,Clear,0.0,25,7,True,Clear Night
4,2024-01-05,23:00,Phoenix,20.0,40,12,Sunny,0.5,70,6,True,Hot
5,2024-01-06,08:00,New York,15.0,60,14,Cloudy,1.2,50,4,False,Cold
6,2024-01-07,12:00,Los Angeles,18.0,75,11,Sunny,0.0,40,3,False,Warm
7,2024-01-08,16:00,Chicago,22.0,50,9,Rainy,5.0,65,5,False,Wet
8,2024-01-09,20:00,Houston,NaN,45,8,Clear,0.0,55,2,True,Clear Night
9,2024-01-10,23:00,Phoenix,30.0,35,7,Sunny,3.0,20,6,True,Hot
10,2024-01-01,08:00,New York,5.0,80,10,Cloudy,2.5,45,2,False,Cold
11,2024-01-02,12:00,Los Angeles,12.0,65,15,Sunny,0.0,30,5,False,Warm
12,2024-01-03,16:00,Chicago,8.0,70,20,Rainy,10.0,60,3,False,Wet
13,2024-01-04,20:00,Houston,NaN,55,5,Clear,0.0,25,7,True,Clear Night
14,2024-01-05,23:00,Phoenix,20.0,40,12,Sunny,0.5,70,6,True,Hot
15,2024-01-06,08:00,New York,15.0,60,14,Cloudy,1.2,50,4,False,Cold
16,2024-01-07,12:00,Los Angeles,18.0,75,11,Sunny,0.0,40,3,False,Warm
17,2024-01-08,16:00,Chicago,22.0,50,9,Rainy,5.0,65,5,False,Wet
18,2024-01-03,16:00,Chicago,8.0,70,20,Rainy,10.0,60,3,False,Wet
19,2024-01-08,16:00,Chicago,22.0,50,9,Rainy,5.0,65,5,False,Wet

In [ ]:
df[['City','Temperature_C']]
#You can select columns according to your need and that too multiple

           City  Temperature_C
0      New York            5.0
1   Los Angeles           12.0
2       Chicago            8.0
3       Houston            NaN
4       Phoenix           20.0
5      New York           15.0
6   Los Angeles           18.0
7       Chicago           22.0
8       Houston            NaN
9       Phoenix           30.0
10     New York            5.0
11  Los Angeles           12.0
12      Chicago            8.0
13      Houston            NaN
14      Phoenix           20.0
15     New York           15.0
16  Los Angeles           18.0
17      Chicago           22.0
18      Chicago            8.0
19      Chicago           22.0

In [26]:
df.loc[df['Weather_Condition']=='Rainy']
#loc function in pandas is a very powerful and useful function,
#we can filter, update, and can even work with conditions.

,Date,Time,City,Temperature_C,Humidity_%,Wind_Speed_kmph,Weather_Condition,Precipitation_mm,Air_Quality_Index,UV_Index,Is_Weekend,Remarks
2,2024-01-03,16:00,Chicago,8.0,70,20,Rainy,10.0,60,3,False,Wet
7,2024-01-08,16:00,Chicago,22.0,50,9,Rainy,5.0,65,5,False,Wet
12,2024-01-03,16:00,Chicago,8.0,70,20,Rainy,10.0,60,3,False,Wet
17,2024-01-08,16:00,Chicago,22.0,50,9,Rainy,5.0,65,5,False,Wet
18,2024-01-03,16:00,Chicago,8.0,70,20,Rainy,10.0,60,3,False,Wet
19,2024-01-08,16:00,Chicago,22.0,50,9,Rainy,5.0,65,5,False,Wet

In [ ]:
df.iloc[2]
#this iloc() function uses integer based indexing

Date                 2024-01-03
Time                      16:00
City                    Chicago
Temperature_C               8.0
Humidity_%                   70
Wind_Speed_kmph              20
Weather_Condition         Rainy
Precipitation_mm           10.0
Air_Quality_Index            60
UV_Index                      3
Is_Weekend                False
Remarks                     Wet
Name: 2, dtype: object

In [33]:
df[df['Weather_Condition']=='Rainy']
#This way you can filter the things that you need based on the conditions

,Date,Time,City,Temperature_C,Humidity_%,Wind_Speed_kmph,Weather_Condition,Precipitation_mm,Air_Quality_Index,UV_Index,Is_Weekend,Remarks
2,2024-01-03,16:00,Chicago,8.0,70,20,Rainy,10.0,60,3,False,Wet
7,2024-01-08,16:00,Chicago,22.0,50,9,Rainy,5.0,65,5,False,Wet
12,2024-01-03,16:00,Chicago,8.0,70,20,Rainy,10.0,60,3,False,Wet
17,2024-01-08,16:00,Chicago,22.0,50,9,Rainy,5.0,65,5,False,Wet
18,2024-01-03,16:00,Chicago,8.0,70,20,Rainy,10.0,60,3,False,Wet
19,2024-01-08,16:00,Chicago,22.0,50,9,Rainy,5.0,65,5,False,Wet

In [ ]:
df.query('Weather_Condition == "Rainy"')
#this function can also be used to filter out the data but in a SQL- like syntax

,Date,Time,City,Temperature_C,Humidity_%,Wind_Speed_kmph,Weather_Condition,Precipitation_mm,Air_Quality_Index,UV_Index,Is_Weekend,Remarks
2,2024-01-03,16:00,Chicago,8.0,70,20,Rainy,10.0,60,3,False,Wet
7,2024-01-08,16:00,Chicago,22.0,50,9,Rainy,5.0,65,5,False,Wet
12,2024-01-03,16:00,Chicago,8.0,70,20,Rainy,10.0,60,3,False,Wet
17,2024-01-08,16:00,Chicago,22.0,50,9,Rainy,5.0,65,5,False,Wet
18,2024-01-03,16:00,Chicago,8.0,70,20,Rainy,10.0,60,3,False,Wet
19,2024-01-08,16:00,Chicago,22.0,50,9,Rainy,5.0,65,5,False,Wet